elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
